Repository tak-st/majang-yakitori, pull requests merged in 2021-11, with the labels that each got.

#35 役のインターフェースを追加
  src/main/java/ckn/yakitori/share/yaku/yaku.java
  src/main/java/ckn/yakitori/share/yaku/yakuInfo.java
Labels: Small

#36 点数計算クラスと計算に必要な情報まとめクラスを追加
  src/main/java/ckn/yakitori/share/mentsu/mentsuPartition.java
  src/main/java/ckn/yakitori/share/score/scoreCalculation.java
  src/main/java/ckn/yakitori/share/score/statusGroup.java
  src/test/java/ckn/yakitori/share/mentsu/mentsuPartitionTest.java
Labels: Large

#37 立直の判定処理の追加
  src/main/java/ckn/yakitori/share/score/scoreCalculation.java
  src/main/java/ckn/yakitori/share/yaku/riichi.java
  src/main/java/ckn/yakitori/share/yaku/yakuInfo.java
  src/test/java/ckn/yakitori/share/yaku/riichiTest.java
Labels: Small

#38 捨て牌エリアクラスのシステム、及びテストを実装しました。
  src/main/java/ckn/yakitori/server/discard/discardArea.java
  src/main/java/ckn/yakitori/server/discard/discardTile.java
  src/test/java/ckn/yakitori/server/discard/discardAreaTest.java
Labels: Small

#39 プレイヤーの点数を変動させる処理です。
  src/main/java/ckn/yakitori/client/player.java
  src/test/java/ckn/yakitori/client/playerTest.java
Labels: Extra Small

#40 ファイルパスを変更しました。
  src/main/java/ckn/yakitori/share/player.java
  src/test/java/ckn/yakitori/share/playerTest.java
Labels: Extra Small

#41 ルールクラスを作成しました。
  src/main/java/ckn/yakitori/share/rule.java
  src/test/java/ckn/yakitori/share/ruleTest.java
Labels: Medium

#44 捨て牌クラスのファイルパスを変更しました。
  src/main/java/ckn/yakitori/share/discard/discardArea.java
  src/main/java/ckn/yakitori/share/discard/discardTile.java
  src/test/java/ckn/yakitori/share/discard/discardAreaTest.java
  src/test/java/ckn/yakitori/share/discard/discardTileTest.java
Labels: Extra Small

#45 コードの所持者を設定した
  .github/CODEOWNERS
Labels: Extra Small

#42 役の判定処理の追加
  src/main/java/ckn/yakitori/share/yaku/bakaze.java
  src/main/java/ckn/yakitori/share/yaku/chun.java
  src/main/java/ckn/yakitori/share/yaku/haku.java
  src/main/java/ckn/yakitori/share/yaku/hatsu.java
  src/main/java/ckn/yakitori/share/yaku/jikaze.java
  src/main/java/ckn/yakitori/share/yaku/riichi.java
  src/test/java/ckn/yakitori/share/yaku/bakazeTest.java
  src/test/java/ckn/yakitori/share/yaku/chunTest.java
  src/test/java/ckn/yakitori/share/yaku/hakuTest.java
  src/test/java/ckn/yakitori/share/yaku/hatsuTest.java
  src/test/java/ckn/yakitori/share/yaku/jikazeTest.java
Labels: Extra Large

#46 刻子槓子両方とも取得するメソッドを追加
  src/main/java/ckn/yakitori/share/score/statusGroup.java
Labels: Extra Small
